### PR TITLE
Create 2016-06-06-gtk3-and-css.md

### PR DESCRIPTION
**Pull request by davelab6**
@eliheuer please check :)

### CODE REVIEW

**Comment by davelab6** [comment]
@eliheuer please check :)

**Comment by samdroid-apps** [comment]
Note that is is CSS for gtk 3.18... Gtk CSS got overhauled in 3.20 to a new, stabilized api

**Comment by davelab6** [comment]
Thanks @samdroid-apps :) Where can we read about what is needed for 3.20... and will 3.20 be available on XO-1s?

**Comment by samdroid-apps** [comment]
3.20 will probably not be on the XO1, unless it gets updated to a recent version.

3.20 is already here or coming to your Fedora's, Debian's and even Ubuntu's.

3.20 just changes the name of the elements.  You can explore it by using the "Css Nodes" view in the Gtk+ inspector.  It is also included in the docs for all the widgets, eg:

> GtkButton has a single CSS node with name button. The node will get the style classes .image-button or .text-button, if the content is just an image or label, respectively. It may also receive the .flat style class.
> 
> Other style classes that are commonly used with GtkButton include .suggested-action and .destructive-action. In special cases, buttons can be made round by adding the .circular style class.
> 
> Button-like widgets like GtkToggleButton, GtkMenuButton, GtkVolumeButton, GtkLockButton, GtkColorButton, GtkFontButton or GtkFileChooserButton use style classes such as .toggle, .popup, .scale, .lock, .color, .font, .file to differentiate themselves from a plain GtkButton.

From https://developer.gnome.org/gtk3/unstable/GtkButton.html

you would use that to do css like:

```
button {
    background: green;
}

button.flat {
    box-shadow: none;
}
```

**Pull request merged**
