### PR TITLE
Added Screenshots and Updated Metadata

### PR DESCRIPTION
**Pull request by aryanharitsh123**

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.

* [x] directory name should be `screenshots`, not `Screenshots`,
* [x] aspect ratio should be 3:4, not 16:9,
* [x] size is best 1024x768 or 1200x900, which you can do by resizing a virtual machine; don't try to resize the image,

**Comment by pro-panda** [comment]
Thanks. Reviewed. 

Looks okay, but the Travis build is failing on ccfb1a7. Try fixing the commit or the Travis files ?

**Review by rhl-bthr — CHANGES_REQUESTED** [review]
Thanks. Reviewed.

Looks okay, but the Travis build is failing on ccfb1a7. Try fixing the commit or the Travis files ?

**Comment by aryanharitsh123** [comment]
I know.. but it is showing an error in code.. I have not edited the code. I have just edited the activity.info file.

**Comment by quozl** [comment]
Thanks.  Reviewed.  Changes are fine by me, and I'd merge, but the repository is configured to refuse this and the CI configuration seems currently broken.  If you think you can fix it, have a go.  It could take days or weeks of work, I don't know.

**Pull request closed without merging**
