### PR TITLE
port from GConf to Gio.Settings

### PR DESCRIPTION
**Pull request by Saumya-Mishra9129**
@quozl The activity is working properly on sugar desktop. Kindly review it however port to Python 3 haven't done yet for this activity. I am working on port from Python2 to Python3 .

### CODE REVIEW

**Comment by Saumya-Mishra9129** [comment]
/EditFonts.py:289:13: E741 ambiguous variable name 'l'
./EditFonts.py:357:9: E722 do not use bare 'except'
./EditFonts.py:374:9: E722 do not use bare 'except'
./EditFonts.py:388:13: E722 do not use bare 'except'
./EditFonts.py:414:13: E722 do not use bare 'except'
./EditFonts.py:464:49: W504 line break after binary operator
./EditFonts.py:522:13: E722 do not use bare 'except'
./EditFonts.py:675:1: E305 expected 2 blank lines after class or function definition, found 1
./editfonts/globals.py:74:1: E305 expected 2 blank lines after class or function definition, found 1
./editfonts/widgets/misc.py:120:74: W504 line break after binary operator
./editfonts/widgets/character_map.py:113:64: W504 line break after binary operator
./editfonts/widgets/render_glyph.py:84:22: F632 use ==/!= to compare str, bytes, and int literals
./editfonts/widgets/render_glyph.py:92:22: F632 use ==/!= to compare str, bytes, and int literals
./editfonts/widgets/render_glyph.py:100:22: F632 use ==/!= to compare str, bytes, and int literals
./editfonts/widgets/drag_point.py:89:43: W504 line break after binary operator
./editfonts/widgets/drag_point.py:90:57: W504 line break after binary operator
./editfonts/widgets/drag_point.py:91:57: W504 line break after binary operator
./editfonts/widgets/drag_point.py:92:59: W504 line break after binary operator
./editfonts/widgets/drag_point.py:110:13: E741 ambiguous variable name 'O'
./editfonts/widgets/drag_point.py:121:61: W504 line break after binary operator
./editfonts/widgets/drag_point.py:122:68: W504 line break after binary operator
./editfonts/ui/manager_page.py:133:57: W504 line break after binary operator
./editfonts/ui/manager_page.py:134:50: W504 line break after binary operator
./editfonts/ui/manager_page.py:294:12: F632 use ==/!= to compare str, bytes, and int literals
./editfonts/ui/manager_page.py:300:14: F632 use ==/!= to compare str, bytes, and int literals
./editfonts/ui/manager_page.py:329:12: F632 use ==/!= to compare str, bytes, and int literals
./editfonts/ui/manager_page.py:331:14: F632 use ==/!= to compare str, bytes, and int literals
./editfonts/ui/create_font_page.py:117:57: W504 line break after binary operator
./editfonts/ui/create_font_page.py:118:73: W504 line break after binary operator
./editfonts/ui/create_font_page.py:119:49: W504 line break after binary operator
./editfonts/core/basefont.py:158:61: W504 line break after binary operator
./editfonts/core/basefont.py:161:64: W504 line break after binary operator
./editfonts/core/basefont.py:196:13: E722 do not use bare 'except'
./editfonts/core/basefont.py:210:9: E722 do not use bare 'except'
2     E305 expected 2 blank lines after class or function definition, found 1
7     E722 do not use bare 'except'
2     E741 ambiguous variable name 'l'
7     F632 use ==/!= to compare str, bytes, and int literals
16    W504 line break after binary operator
The command "flake8 --statistics  --ignore=E402,E501 --exclude=defcon,extractor,fontTools,fontmake,robofab,ufo2ft,ufoLib,snippets,docs,compreffor,booleanOperations,cu2qu,fontMath,glyphsLib,mutatorMath ." exited with 1.
Done. Your build exited with 1.

I am getting this in travis CI. I am not able to understand what's it about?

**Comment by quozl** [comment]
I didn't think the activity was working yet.  If it is working, is it ready to be published?  See the other issues in the repository.

**Comment by ayushnawal** [comment]
Thanks @Saumya-Mishra9129 but unfortunately continuous integration isn't working in this activity :sweat: 

CI configuration seems currently broken, you can try fixing it but I assume it will be a hard task.

**Comment by srevinsaju** [comment]
Travis is failing because of 

https://github.com/sugarlabs/edit-fonts-activity/blob/5573a4b139d703bff70a78f3bb5a0a4a6cb6b1a2/.travis.yml#L7-L8

**Comment by Saumya-Mishra9129** [comment]
> Travis is failing because of
> 
> https://github.com/sugarlabs/edit-fonts-activity/blob/5573a4b139d703bff70a78f3bb5a0a4a6cb6b1a2/.travis.yml#L7-L8

Thanks @srevinsaju .

**Comment by srevinsaju** [comment]
@Saumya-Mishra9129 Travis is still failing. Seems like there are some important flake fixes to be done yet. 
Run
```bash
flake8
```
and check for errors / warnings.
I guess, unless there are not a single warning, the CI will not pass this PR, even though it is outside the scope of this PR

**Comment by Saumya-Mishra9129** [comment]
I have tried to fix CI configuration here. @quozl Review once.

**Comment by quozl** [comment]
Thanks.  I don't think the activity has been finished and released.  It isn't an activity I've focused on.  But in the absence of any other reviewers, I'll just merge anyway now that I can.

**Pull request merged**
